
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.EventQueue;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.geom.Area;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import java.awt.*;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.*;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import com.sun.awt.AWTUtilities;



/**
 *
 * @author ericzhu
 */
public class TXESHOT extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;


	/**
     * Creates new form TXESHOT
     */
    public TXESHOT() {
        initComponents();
        this.setAlwaysOnTop(false);
        jTextArea3.setText(fileName);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
   
    private JFileChooser dialog = new JFileChooser(System.getProperty("home.dir"));
   
    private String fileName = "TxeScreenShot1.png"; 
   
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jButton1.setText("jButton1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        jTabbedPane1.setToolTipText("Screenshot");
        jTabbedPane1.addTab("Picture", jLabel1);

        jTabbedPane4.setEnabled(false);
        jTabbedPane4.addTab("Picture 2", jLabel3);

        jTabbedPane1.addTab("Picture 2", jTabbedPane4);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText(fileName);
        jScrollPane3.setViewportView(jTextArea3);

        jTabbedPane2.addTab("Picture Name 1", jScrollPane3);
        jTabbedPane2.addTab("Picture Name 2", jTabbedPane3);

        jTabbedPane1.addTab("Name", jTabbedPane2);

        jMenu2.setText("Screenshot");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Take Screenshot");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Screenshot");

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    
    
    private Image scaledImage(Image img, int w, int h){
    BufferedImage resized = new BufferedImage(w, h, BufferedImage.TYPE_INT_RGB);
    Graphics2D graph2d = resized.createGraphics();
    graph2d.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
    graph2d.drawImage(img, 0, 0, w, h, null);
    graph2d.dispose();
    return resized;
    }
  
    public void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        
    	this.setVisible(false);
        
    	this.setAlwaysOnTop(false);
    	
         
        
        
         
         try{
         
         Rectangle screenshotRect = new Rectangle(Toolkit.getDefaultToolkit().getScreenSize());
         BufferedImage Capture = new Robot().createScreenCapture(screenshotRect);
         ImageIcon pic = new ImageIcon(scaledImage(Capture, jLabel3.getWidth(), jLabel3.getHeight()));
         ImageIO.write(Capture, "png", new File(fileName));
          
         jLabel3.setIcon(pic);
          
        
           
          
        
         }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
           
     }
         try{
       	   Thread.currentThread();
   		
       	   Thread.sleep(1000);
       	   
       	 }
       	 catch(InterruptedException ie){
       	 
       	 }
         this.setVisible(true);
                                                   
    }
   
  
    @SuppressWarnings("empty-statement")
    public void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       this.setVisible(false);
      this.setAlwaysOnTop(false);
       
       try{
    	   Thread.currentThread();
		
    	   Thread.sleep(1000);
    	   
    	 }
    	 catch(InterruptedException ie){
    	 
    	 }
        
        this.setVisible(true);
        
        try{
        
        Rectangle screenshotRect = new Rectangle(Toolkit.getDefaultToolkit().getScreenSize());
        BufferedImage Capture = new Robot().createScreenCapture(screenshotRect);
        ImageIcon pic = new ImageIcon(scaledImage(Capture, jLabel1.getWidth(), jLabel1.getHeight()));
        ImageIO.write(Capture, "png", new File(fileName));
         
           jLabel1.setIcon(pic);
         
         
          
         
       
        }catch(Exception ex){
           JOptionPane.showMessageDialog(null, ex);
           
    }//GEN-LAST:event_jMenuItem1ActionPerformed
   }
  

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TXESHOT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TXESHOT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TXESHOT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TXESHOT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TXESHOT().setVisible(true);
            }
        });
    }
    

    
}
